##############################################
#      UltimateBlood Configuration File      #
##############################################
# Language (supported right now: en, es, de, fr, ru)
language: "es"
# Enable or disable blood particles
enable-blood-particles: true

# Enable or disable bleeding effect
bleeding: true
heavy-bleeding: true

# Damage
bleeding-damage: 2.0
heavy-bleeding-damage: 5.0

# Duration of bleeding effect in ticks (1 second = 20 ticks)
bleeding-duration: 1000

#Bandage configurable recipe, ingredients must be in UPPER CASE
#Another example of a bandage craft recipe
#bandage-recipe:
#  shape:
#    - " S "
#    - " P "
#    - " S "
#  ingredients:
#    S: STRING
#    P: PAPER
bandage-recipe:
  shape:
    - "PPP"
    - "PMP"
    - "PPP"
  ingredients:
    M: PHANTOM_MEMBRANE
    P: PAPER

# Disable bleeding mechanics in these worlds
disabled-worlds:
  - world_nether
  - world_the_end
  - spawn_world

#Mob configuration
player:
  Enabled: true
  BloodType: REDSTONE_BLOCK

passive:
  Enabled: true

neutral:
  Enabled: true

hostile:
  Enabled: true

boss:
  Enabled: true

passive-mobs:
  Allay: REDSTONE_BLOCK
  Bat: REDSTONE_BLOCK
  Cat: REDSTONE_BLOCK
  Chicken: REDSTONE_BLOCK
  Cod: REDSTONE_BLOCK
  Cow: REDSTONE_BLOCK
  Donkey: REDSTONE_BLOCK
  Fox: REDSTONE_BLOCK
  GlowingSquid: REDSTONE_BLOCK
  Horse: REDSTONE_BLOCK
  Mule: REDSTONE_BLOCK
  Ocelot: REDSTONE_BLOCK
  Parrot: REDSTONE_BLOCK
  Pig: REDSTONE_BLOCK
  PolarBear: REDSTONE_BLOCK
  PufferFish: REDSTONE_BLOCK
  Rabbit: REDSTONE_BLOCK
  Salmon: REDSTONE_BLOCK
  Sheep: REDSTONE_BLOCK
  Squid: REDSTONE_BLOCK
  Strider: REDSTONE_BLOCK
  TropicalFish: REDSTONE_BLOCK
  Turtle: REDSTONE_BLOCK
  Villager: REDSTONE_BLOCK
  WanderingTrader: REDSTONE_BLOCK

neutral-mobs:
  Bee: REDSTONE_BLOCK
  Dolphin: REDSTONE_BLOCK
  Enderman: REDSTONE_BLOCK
  Goat: REDSTONE_BLOCK
  IronGolem: IRON_BLOCK
  Llama: REDSTONE_BLOCK
  Panda: REDSTONE_BLOCK
  PolarBear: REDSTONE_BLOCK
  TraderLlama: REDSTONE_BLOCK
  Wolf: REDSTONE_BLOCK
  ZombifiedPiglin: REDSTONE_BLOCK

hostile-mobs:
  Blaze: REDSTONE_BLOCK
  Breeze: REDSTONE_BLOCK
  Bogged: REDSTONE_BLOCK
  Creeper: REDSTONE_BLOCK
  Drowned: REDSTONE_BLOCK
  CaveSpider: REDSTONE_BLOCK
  Endermite: REDSTONE_BLOCK
  Evoker: REDSTONE_BLOCK
  Ghast: REDSTONE_BLOCK
  Guardian: REDSTONE_BLOCK
  Hoglin: REDSTONE_BLOCK
  Husk: REDSTONE_BLOCK
  MagmaCube: REDSTONE_BLOCK
  Phantom: REDSTONE_BLOCK
  Piglin: REDSTONE_BLOCK
  Pillager: REDSTONE_BLOCK
  Ravager: REDSTONE_BLOCK
  Shulker: REDSTONE_BLOCK
  SilverFish: REDSTONE_BLOCK
  Skeleton: BONE_BLOCK
  Slime: SLIME_BLOCK
  Spider: REDSTONE_BLOCK
  Stray: REDSTONE_BLOCK
  Vex: REDSTONE_BLOCK
  Vindicator: REDSTONE_BLOCK
  Witch: REDSTONE_BLOCK
  WitherSkeleton: COAL_BLOCK
  Zombie: REDSTONE_BLOCK
  ZombieVillager: REDSTONE_BLOCK
boss-mobs:
  EnderDragon: REDSTONE_BLOCK
  ElderGuardian: REDSTONE_BLOCK
  Warden: REDSTONE_BLOCK
  Wither: REDSTONE_BLOCK